# Generated by Django 4.0.6 on 2022-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSCrypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='img',
            field=models.URLField(default='#'),
        ),
    ]
