# Generated by Django 4.0.6 on 2022-12-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VSCrypto', '0002_coin_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='img',
        ),
    ]
